spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://localhost:3306/sell?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8081
env:
  dev2
